app/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path

from rest_framework import routers

from . import views

urlpatterns = [
    # Landing
    path("", views.IndexView.as_view(), name='index'),

    # Signups/Account pages
    path("accounts/password_reset/", auth_views.PasswordResetView.as_view(
        html_email_template_name="registration/password_reset_email_html.html"
    )),
    path("accounts/", include('django.contrib.auth.urls')),
    path("accounts/signup/<uuid:signup_invite>", views.UserSignupView.as_view(), name='user_signup'),
    path("accounts/signup/", views.UnrestrictedUserSignupView.as_view(), name='unrestricted_user_signup'),
    path("dashboard/game-signup", views.GameSignupView.as_view(), name='game_signup'),
    path("dashboard/volunteer/signup-players", views.SignupPlayersView.as_view(), name='signup_players'),
    path("dashboard/strong_volunteer/signup-players", views.BetterSignupPlayersView.as_view(), name='better_signup_players'),
    path("signup/<uuid:signup_invite>", views.signup, name='signup'),
    path("game-signup/<uuid:signup_invite>", views.TokenRequiredGameSignupView.as_view(), name='token_game_signup'),

    # Default dashboard pages
    path("dashboard", views.DashboardView.as_view(), name='dashboard'),
    path("missions", views.MissionsView.as_view(), name='missions'),
    path("previous-games", views.PrevGamesView.as_view(), name='previous_games'),
    path("guide", views.NewPlayerGuideView.as_view(), name='new_player_guide'),
    path("minecraft", views.MinecraftView.as_view(), name='minecraft'),

    # Player/Game pages
    path("dashboard/player", views.PlayerInfoView.as_view(), name='player_info'),
    path("dashboard/player-code", views.PlayerCodeView.as_view(), name='player_code'),
    path("dashboard/change-code", views.ChangeCodeView.as_view(), name='change_code'),
    path("dashboard/claim-supply-code", views.ClaimSupplyCodeView.as_view(), name='claim_supply_code'),
    path("dashboard/report-tag", views.ReportTagView.as_view(), name='report_tag'),
    path("dashboard/view-tags", views.PlayerTagView.as_view(), name='view_tags'),
    path("dashboard/player-list", views.PlayerListView.as_view(), name='player_list'),
    path("dashboard/message-players", views.MessagePlayersView.as_view(), name='message_players'),
    path("dashboard/zombie-tree", views.ZombieTreeView.as_view(), name='zombie_tree'),

    # Moderator pages
    path("dashboard/moderator/generate-supply-codes", views.GenerateSupplyCodesView.as_view(),
         name='generate_supply_codes'),
    path("dashboard/moderator/manage-game", views.ManageGameView.as_view(), name='manage_game'),

    path("dashboard/moderator/game-start", views.GameStartView.as_view(), name='game_start'),
    path("dashboard/moderator/game-set", views.GameSetView.as_view(), name='game_set'),
    path("dashboard/moderator/game-end", views.GameEndView.as_view(), name='game_end'),
    path("dashboard/moderator/kill-unsupplied-humans", views.KillUnsuppliedHumansView.as_view(),
         name='kill_unsupplied_humans'),

    path("dashboard/moderator/add-signup", views.ManageSignupView.as_view(),
         name='manage_signup'),
    path("dashboard/moderator/manage-oz", views.ManageOZView.as_view(), name='manage_oz'),
    path("dashboard/moderator/manage-players", views.ManagePlayersView.as_view(), name='manage_players'),
    path("dashboard/moderator/player-search", views.PlayerSearchView.as_view(), name='player_search'),
    path("dashboard/moderator/manage-shop", views.ManageShopView.as_view(), name='manage_shop'),
    path("dashboard/moderator/stun-verification", views.StunVerificationView.as_view(), name='stun_verification'),
    path("dashboard/moderator/delete-factions", views.DeleteFactionsView.as_view(), name="delete_factions"),
    path("dashboard/moderator/manage_factions", views.ManageFactionsView.as_view(), name="manage_factions"),

    # Necromancer pages
    path("dashboard/moderator/manage-staff", views.ManageStaffView.as_view(), name='manage_staff'),
    path("dashboard/moderator/manage-legacy", views.ManageLegacyView.as_view(), name='manage_legacy'),
    path("dashboard/moderator/manage-mods", views.ManageModsView.as_view(), name='manage_mods'),
    path("dashboard/moderator/manage-volunteers", views.ManageVolunteersView.as_view(), name='manage_volunteers'),
    path("dashboard/moderator/email-templates", views.EmailTemplatesView.as_view(), name='email_templates'),
    
    # API
    path("api/v1/", include('app.api.urls')),

    # Impersonation
    re_path(r'^su/', include('django_su.urls')),
]

uwhvz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
#from wagtail.admin import urls as wagtailadmin_urls
#from wagtail.core import urls as wagtail_urls
#from wagtail.documents import urls as wagtaildocs_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('app.urls')),
    #path("cms/", include(wagtailadmin_urls)),
    #path("documents/", include(wagtaildocs_urls)),
    #path("", include(wagtail_urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models/moderator.py
from django.db import models

from .game import Game
from .participant import Participant
from .user import User


class ModeratorManager(models.Manager):
    def create_moderator(self, user: User, game: Game, **extra_fields) -> 'Moderator':
        if user.participant(game):
            raise ValueError(f"The user {user} already exists in the game {game}.")

        moderator = self.model(user=user, game=game, **extra_fields)

        moderator.save()
        return moderator


class Moderator(Participant):
    character_name: str = models.CharField("Character name", max_length=180, blank=True, null=True)
    score: str = models.CharField("Moderator 'score'. Can include letters.", max_length=180, blank=True, null=True)

    objects = ModeratorManager()

    @property
    def is_moderator(self):
        return True

    def __str__(self):
        return self.character_name if self.character_name else self.user.get_full_name()

app/models/purchase.py
import uuid
from datetime import datetime

from django.db import models

from .game import Game
from .player import Player


class PurchaseManager(models.Manager):
    def create_purchase(self, buyer: Player, cost: int, game: Game, details: str) -> 'Purchase':
        purchase = self.model(buyer=buyer, cost=cost, game=game, details=details)
        purchase.save()
        return purchase


class Purchase(models.Model):
    id: uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    game: Game = models.ForeignKey(Game, on_delete=models.CASCADE)
    cost: int = models.IntegerField()
    details: str = models.CharField(blank=True,max_length=50)
    
    buyer: Player = models.ForeignKey(Player, on_delete=models.CASCADE, null=True, blank=True, related_name='buyer_name')
    
    active: bool = models.BooleanField(default=True)

    time: datetime = models.DateTimeField(auto_now_add=True)
    created_at: datetime = models.DateTimeField(auto_now_add=True)
    modified_at: datetime = models.DateTimeField(auto_now=True)

    objects = PurchaseManager()

    def __int__(self):
        return self.cost

app/views/dashboard.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.utils.decorators import method_decorator
from django.shortcuts import redirect, render
from django.views import View
from rest_framework.utils import json
from django.contrib.auth.models import Group
from django.contrib import messages
from time import mktime
from datetime import datetime
import pytz

from app.util import MobileSupportedView, most_recent_game
from app.models import Game, Tag, Player, PlayerRole, SignupLocation, Legacy, SupplyCode, User, TagType, Email, RecipientGroup
from app.views.forms import ChangeCodeForm

class IndexView(MobileSupportedView):
    desktop_template = "index.html"
    mobile_template = "mobile/index.html"

    def get(self, request):
        game = most_recent_game()
        signups = SignupLocation.objects.filter(game=game).exclude(name='Online')
        if game and game.started_on:
            for_js = int(mktime(game.started_on.timetuple())) * 1000
        else:
            for_js = int(mktime(datetime.utcnow().timetuple())) * 1000
        return self.mobile_or_desktop(request, {'game': game, 'signups':signups, 'for_js':for_js})


@method_decorator(login_required, name='dispatch')
class DashboardView(MobileSupportedView):
    desktop_template = "dashboard/index.html"
    mobile_template = "mobile/dashboard/index.html"

    def get(self, request, change_code_form=ChangeCodeForm()):
        game = most_recent_game()
        participant = request.user.participant(game)
        stuns = Tag.objects.filter(initiator__user=request.user,type=TagType.STUN,active=True).count()
        kills = Tag.objects.filter(initiator__user=request.user,type=TagType.KILL,active=True).count()
        codes = SupplyCode.objects.filter(claimed_by__user=request.user,active=True).count()

        emails = Email.objects.filter(game=game,visible=True)
        if participant and participant.is_player:
            if participant.is_human:
                emails = emails.exclude(group=RecipientGroup.ZOMBIE)
            elif participant.is_zombie:
                emails = emails.exclude(group=RecipientGroup.HUMAN)
            elif participant:
                emails = Email.objects.filter(game=game)
            else:
                emails = None
            # Exclude direct message emails not intended for this user
            emails = emails.exclude(~Q(target_player_code=participant.code), group=RecipientGroup.USER)
        else:
            # If not a participant, exclude direct emails
            emails = emails.exclude(group=RecipientGroup.USER)

        if emails:
            emails.order_by("-created_at")
            if not request.user.groups.filter(name='LegacyUsers').exists() and not request.user.groups.filter(name='Volunteers').exists():
                emails = emails.exclude(group=RecipientGroup.VOLUNTEER)
        
        ## Okay so this is super janky and we really need an object that can handle just general storage of text so we can update stuff as we like.
        ## But seeing as that isn't around right now... we're going to use the email object instead.
        if not Email.objects.filter(name="Dashboard Welcome (Visible only to Mods)",game=game).exists():
            Email.objects.create_email("Dashboard Welcome (Visible only to Mods)",'Please check back later for info regarding the game start!',RecipientGroup.ALL,game,visible=False)
        dashboard_welcome = Email.objects.get(name="Dashboard Welcome (Visible only to Mods)",game=game).data
        
        points_accu = sum(Legacy.objects.filter(user=request.user,value__gt=0).values_list('value', flat=True))
        # Only spot this variable exists/is used. This should probably be moved to config/settings.
        points_for_permanent = 6
        if game.is_running and (request.user.is_superuser or (request.user.participant(game) and request.user.participant(game).is_moderator)):
            unverified = Tag.objects.filter(initiator__game=game,
                receiver__game=game,active=False).count()
            if unverified:
                messages.error(request, f"There are {unverified} tags that require verification")
        return self.mobile_or_desktop(request, {'game': game, 'participant': participant, 'change_code_form': change_code_form,
                                                'stuns':stuns, 'kills':kills, 'codes':codes, 'emails':emails.order_by("-created_at") if emails else None, 'pytz':pytz,
                                                'points_accu':points_accu, 'points_for_permanent':points_for_permanent, 'dashboard_welcome':dashboard_welcome})

    def post(self, request):
        game = most_recent_game()

        if "pts" in request.POST:
            player = request.user.participant(game)
            player.point_modifier = 15 # This should also be moved to config or settings
            player.save()
            Legacy.objects.create_legacy(user=request.user,value=-1,details=f'Started {game} game with 15 points.')
            messages.success(request, "You will now start the game with 15 points.")

        elif "oz" in request.POST:
            player = request.user.participant(game)
            player.is_oz = True
            player.save()
            Legacy.objects.create_legacy(user=request.user,value=-1,details=f'Started {game} game as OZ.')
            messages.success(request, "You will now start the game as OZ.")

        legacy_users = Group.objects.get(name='LegacyUsers')
        if request.user.id not in list(User.objects.filter(groups__name="LegacyUsers").values_list('id', flat=True)):
            legacy_users.user_set.add(request.user)

        return redirect('dashboard')



class MissionsView(MobileSupportedView):
    desktop_template = "missions.html"
    mobile_template = "missions.html"    

    def get(self, request):
        game = most_recent_game()
        return self.mobile_or_desktop(request, {'game': game})

class MinecraftView(MobileSupportedView):
    desktop_template = "minecraft.html"
    mobile_template = "minecraft.html"

    def get(self, request):
        game = most_recent_game()
        return self.mobile_or_desktop(request, {'game': game})
    
class NewPlayerGuideView(MobileSupportedView):
    desktop_template = "new_player_guide.html"
    mobile_template = "new_player_guide.html"    

    def get(self, request):
        game = most_recent_game()
        return self.mobile_or_desktop(request, {'game': game})

class PrevGamesView(View):
    template_name = "previous_games.html"

    def render_zombie_tree(self, request, prev_games, game):

        player_codes = {}
        nodes = {}
        edges = []
        tag_descs = {}
        # Since we don't want repeated instances of OZs, we use a set instead of a list.
        ozs = set()

        tags = Tag.objects.filter(
            initiator__game=game,
            receiver__game=game,
            type=TagType.KILL,
            active=True)

        for tag in tags:
            if tag.location:
                desc = tag.location
                if tag.description:
                    desc = desc + ': ' + tag.description
            else:
                desc = tag.description
            edges.append({'from': tag.initiator.code, 'to': tag.receiver.code})
            tag_descs[tag.receiver.code] = desc

            player_codes[tag.initiator.code] = tag.initiator.user.get_full_name()
            player_codes[tag.receiver.code] = tag.receiver.user.get_full_name()

        nodes['NECROMANCER'] = {'label': "Necromancer",'title':"Necromancer"}
        for oz in Player.objects.filter(game=game,is_oz=True):
            if oz not in ozs:
                ozs.add(oz)
        oz_codes = []
        for oz in ozs:
            edges.append({'from': 'NECROMANCER', 'to': oz.code})
            player_codes[oz.code] = oz.user.get_full_name()
            oz_codes.append(oz.code)

        for code, name in player_codes.items():
            nodes[code] = {'label': name}
            if code in oz_codes:
                nodes[code]['title'] = 'OZ'
            if code in tag_descs:
                desc = tag_descs[code]
                if desc.strip():
                    desc = desc.split()
                    desc.reverse()
                    to_write = ['']
                    while desc:
                        curr_len = len(to_write[-1])
                        next_word = desc.pop()
                        if curr_len + len(next_word) <= 100:
                            to_write[-1] += ' ' + next_word
                        else:
                            to_write[-1] += "</br>"
                            to_write.append(next_word)
                    nodes[code]['title'] = ''.join(to_write)
                    #nodes[code]['title'] = '<span style="display: -webkit-box;word-wrap:break-word;word-break: break-all;overflow-x: auto;">' + ''.join(to_write) + '</span>'
                else:
                    nodes[code]['title'] = ':/'

        # BFS on the edge list so that we can put each node into a group based on
        # its level in the tree.
        # This is perhaps the only time you will see a practical use of BFS
        queue = ['NECROMANCER']
        level = 0
        while queue:
            popped = []
            while queue:
                node_id = queue.pop(0)
                popped.append(node_id)
                nodes[node_id]['group'] = level
            children = []
            while popped:
                node_id = popped.pop(0)
                children.extend([n['to'] for n in edges if n['from'] == node_id])

            queue.extend(children)
            level += 1

        node_list = []
        for key, value in nodes.items():
            node_list.append({'id': key, **value})

        return render(request, self.template_name, {
            'game_rendering': game,
            'prev_games':prev_games,
            'nodes': json.dumps(node_list),
            'edges': json.dumps(edges),
        })

app/templates/jinja2/dashboard/moderator/email_templates.html
{% from "components/card.html" import card %}
{% extends "dashboard/base.html" %}

{% block title %}Necro Dashboard &mdash; Email Template Modification{% endblock %}
{% block pagetitle %}{{ game }} &mdash; Necro Actions{% endblock %}
{% block pagesubtitle %}Email Template Modification{% endblock %}

{% block subcontent %}
<div class="ui-grid">
  {% call card("Warning on altering emails") %}
  <p>Anything in double curly brackets is code that will be evaluated when the emails are sent. Do not try to change the code or add new parts with curly brackets unless you're certain you know what you're doing. You have been warned. It's recommended you only change the &lt;body&gt; of the html code.</p>
  <p>Also, a brief note on html code if you don't know how it works: use the &lt;p&gt; to start a paragraph, and &lt;/p&gt; to end a paragraph. Using &lt;b&gt; and &lt;i&gt; will bold or italicize text, respectively. Hitting enter won't start a new paragraph - only &lt;p&gt; will. If you need a space in the email for some reason, insert a break with &lt;br&gt;. It's recommended you plug html code into a viewer just to be sure you know what it'll look like before you use it.</p>
  {% endcall %}
  
  
  
    {% call card("Signup Email") %}
    <form action="{{ url('email_templates') }}" method="post" novalidate>
      {{ csrf_input }}
       {% for field in signup_email_form %}
        <div class="ui-form-group">
        <label class="ui-label" for="{{ field.name }}">{{ field.label }}</label>
          {{ field }}
          {% for error in field.errors %}
            <span class="ui-form__text ui-form__text--error">{{ error }}</span>
          {% endfor %}
        </div>
      {% endfor %}
       <div class="ui-form-group pt-2">
        <input class="btn btn-block btn-primary" type="submit" value="Save" name="change_signup">
      </div>
    </form>
    {% endcall %}
    
    {% call card("Reminder Email") %}
      <form action="{{ url('email_templates') }}" method="post" novalidate>
      {{ csrf_input }}
       {% for field in reminder_email_form %}
        <div class="ui-form-group">
        <label class="ui-label" for="{{ field.name }}">{{ field.label }}</label>
          {{ field }}
          {% for error in field.errors %}
            <span class="ui-form__text ui-form__text--error">{{ error }}</span>
          {% endfor %}
        </div>
      {% endfor %}
       <div class="ui-form-group pt-2">
        <input class="btn btn-block btn-primary" type="submit" value="Save" name="change_reminder">
      </div>
    </form>
      <div class="ui-form-group">
        <button class="btn btn-block btn-primary" data-toggle="modal" data-target="#ReminderModal">Send Reminder Email</button>
      </div>
    {% endcall %}
    
    {% call card("Game Start Email") %}
      <form action="{{ url('email_templates') }}" method="post" novalidate>
      {{ csrf_input }}
       {% for field in start_email_form %}
        <div class="ui-form-group">
        <label class="ui-label" for="{{ field.name }}">{{ field.label }}</label>
          {{ field }}
          {% for error in field.errors %}
            <span class="ui-form__text ui-form__text--error">{{ error }}</span>
          {% endfor %}
        </div>
      {% endfor %}
       <div class="ui-form-group pt-2">
        <input class="btn btn-block btn-primary" type="submit" value="Save" name="change_start">
      </div>
    </form>
    <p>Note: You can also send a game start email through the message players tab if you like!</p>
    <table><tr><td>
       <div class="ui-form-group">
        <form class="mb-0" action="{{ url('email_templates') }}" method="post">
          {{ csrf_input }}
          <input type="submit" class="btn btn-primary" value="Test Start Email" name="test_start">
        </form>
      </div>
      </td><td>
      <div class="ui-form-group">
        <button class="btn btn-block btn-primary" data-toggle="modal" data-target="#StartModal">Send Start Email</button>
      </div>
    </td></tr></table>
    {% endcall %}
</div>

<div class="modal" id="ReminderModal" tabindex="-1" role="dialog" aria-labelledby="ReminderModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title">Are you sure you want to send a reminder email?</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>A reminder email will send to all players who haven't followed their link. This is irreversible. Do not spam it.</p>
        <p>Please ensure you have changed both the HTML <i>and</i> the txt files!</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">No, Cancel</button>
        <form class="mb-0" action="{{ url('email_templates') }}" method="post">
          {{ csrf_input }}
          <input type="submit" class="btn btn-primary" value="Send Reminder Email" name="send_reminder">
        </form>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="StartModal" tabindex="-1" role="dialog" aria-labelledby="StartModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title">Are you sure you want to send a game start email?</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>A game start email will send to all players who are signed up. <b>The game should be started prior to pressing this button.</b> This is irreversible. You should almost never have to use this twice.</p>
        <p>Please ensure you have changed the HTML file!</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">No, Cancel</button>
        <form class="mb-0" action="{{ url('email_templates') }}" method="post">
          {{ csrf_input }}
          <input type="submit" class="btn btn-primary" value="Send Start Email" name="send_start">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/jinja2/dashboard/moderator/generate_supply_codes.html
{% from "components/card.html" import card %}
{% extends "dashboard/base.html" %}

{% block title %}Mod Dashboard &mdash; Generate Supply Codes{% endblock %}
{% block pagetitle %}{{ game }} &mdash; Moderator Actions{% endblock %}
{% block pagesubtitle %}Generate Supply Codes{% endblock %}

{% block subcontent %}
<div class="ui-grid s-dashboard__generate-supply">
  <div class="ui-grid align-content-start">
    {% call card("Generate Supply Codes", class="text-center") %}
      <form action="{{ url('generate_supply_codes') }}" method="post" novalidate>
        {{ csrf_input }}
        
        {% for field in make_codes_form %}
          <div class="ui-form-group">
            <label class="ui-label" for="{{ field.name }}">{{ field.label }}</label>
            {{ field }}
            {% if field.help_text %}
              <span class="ui-form__text ui-form__text--info">{{ field.help_text }}</span>
            {% endif %}
            {% for error in field.errors %}
              <span class="ui-form__text ui-form__text--error">{{ error }}</span>
            {% endfor %}
            </div>
          {% endfor %}
      
        <div class="ui-form-group pt-2">
          <input type="submit" value="Generate Supply Code" class="btn btn-block btn-primary">
        </div>
      </form>
    {% endcall %}
  </div>
  
  <div class="ui-grid">
    {% call card("Unclaimed Codes") %}
      <table class="table table-striped">
      <tr><td>Code ID</td><td>Value</td></tr>
      
        {% for code in supply_codes %}
          {% if code.claimed_by is none %}
            <tr>
              <td>{{ code.code }}</td>
              <td>{{ code.value }}</td>
            </tr>
          {% endif %}
        {% endfor %}
      </table>
    {% endcall %}
  </div>
</div>
{% endblock %}

app/templates/jinja2/dashboard/moderator/manage_shop.html
{% from "components/card.html" import card %}
{% extends "dashboard/base.html" %}

{% block title %}Mod Dashboard &mdash; Manage Shop{% endblock %}
{% block pagetitle %}{{ game }} &mdash; Moderator Actions{% endblock %}
{% block pagesubtitle %}Manage Shop{% endblock %}

{% block subcontent %}
<div class="ui-grid s-dashboard__generate-supply">
  <div class="ui-grid align-content-start">
    {% call card("Make Sale", class="text-center") %}
      <form action="{{ url('manage_shop') }}" method="post" novalidate>
        {{ csrf_input }}
        
        {% for field in make_sale_form %}
          <div class="ui-form-group">
            <label class="ui-label" for="{{ field.name }}">{{ field.label }}</label>
            {{ field }}
            {% if field.help_text %}
              <span class="ui-form__text ui-form__text--info">{{ field.help_text }}</span>
            {% endif %}
            {% for error in field.errors %}
              <span class="ui-form__text ui-form__text--error">{{ error }}</span>
            {% endfor %}
            </div>
          {% endfor %}
      
        <div class="ui-form-group pt-2">
          <input type="submit" value="Make Sale" class="btn btn-block btn-primary">
        </div>
      </form>
    {% endcall %}
  </div>
  
  <div class="ui-grid">
    {% call card("Purchases") %}
      <table class="table table-striped">
      <tr><td>Buyer</td><td>Purchase</td><td>Cost</td><td>Day</td></tr>
      
        {% for sale in all_sales %}
          {% if sale.active %}
            <tr>
              <td>{{ sale.buyer }}</td>
              <td>{{ sale.details }}</td>
              <td>{{ sale.cost }}</td>
              <td>{{ sale.time.astimezone(tz).strftime("%Y-%m-%d %H:%M") }}</td>
          {% endif %}
        {% endfor %}
      </table>
    {% endcall %}
  </div>
</div>
{% endblock %}

app/templates/jinja2/dashboard/moderator/player_search.html
{% from "components/card.html" import card %}
{% extends "dashboard/base.html" %}

{% block title %}Mod Dashboard &mdash; Player Search{% endblock %}

{% block pagetitle %}{{ game }} &mdash; Moderator Actions{% endblock %}
{% block pagesubtitle %}Player Search{% endblock %}


{% block subcontent %}
    {% call card('Player Search', class='align-self-start') %}
        {% with search_input="" %}
            <form action="player-search" method="post">
                {{ csrf_input }}
                {{ search_form }}
                <input class="btn btn-primary" type="submit" value="Search"/>
            </form>
        {% endwith %}
        {% if player %}
            <h3 class="faction-name">Results for Code: {{ input_code }}</h3>
                <table class="table table-striped">
                  <thead>
                    <tr>
                      <th scope="col">Name</th>
                      <th scope="col">Email</th>
                      <th scope="col">Code</th>
                      <th scope="col">Role</th>
                      <th scope="col">Faction</th>
                      <th scope="col">Shop Score</th>
                      <th scope="col">True Score</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td scope="col">
                          {% if player.is_moderator and player.character_name %}
                              {{ player.character_name }}
                          {% else %}
                              {{ player.user.get_full_name() }}
                          {% endif %}</td>
                      <td scope="col">{{ player.user.email }}</td>
                      <td scope="col">{% if player.is_player %}{{ player.code }}{% else %}N/A{% endif %}</td>
                      <td scope="col">{% if player.is_player %}{{ player.role }}{% else %}{{ player.type }}{% endif %}</td>
                      <td scope="col">{% if player.is_player and player.faction %}{{ player.faction.name }}{% else %}N/A{% endif %}</td>
                      {% if player.is_player %}
                        <td scope="col">{{ player.shop_score() }}</td>
                        <td scope="col">{{ player.score() }}</td>
                      {% else %}
                        <td scope="col">N/A</td>
                        <td scope="col">{{ player.score if player.is_moderator and player.score else 'N/A' }}</td>
                      {% endif %}
                    </tr>
                  </tbody>
                </table>
                <span>
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th scope="col">Supply Code</th>
                          <th scope="col">Code Value</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for code in supplycode_set %}
                            <tr>
                                <td>{{ code.code }}</td>
                                <td>{{ code.value }}</td>
                            </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th scope="col">Store Purchase</th>
                          <th scope="col">Purchase Time</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for purchase in purchase_set %}
                            <tr>
                                <td>{{ purchase.details }}</td>
                                <td>{{ purchase.time if purchase.time else 'Unknown' }}</td>
                            </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                </span>
        {% endif %}
    {% endcall %}
{% endblock %}